

stages:
 - deploy-scratch
 - delete-scratch
 - deploy-sandbox
 - deploy-production

Deploy Scratch Org:
  stage: deploy-scratch
  only:
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
      - $DEPLOY_SCRATCH_ON_EVERY_COMMIT == 'true'
  except:
    variables:
      - $SCRATCH_DISABLED
  script:
    - setup_sfdx
    - if ! check_daily_scratch_orgs $SF_USERNAME; then exit 1; fi
    - create_scratch_org
    - push_to_scratch_org_and_test
    - echo "$scratch_org_username" > SCRATCH_ORG_USERNAME.txt
    - populate_url_artifact "$scratch_org_username"
    - echo "$environment_html" > ENVIRONMENT.html
  artifacts:
    paths:
      - SCRATCH_ORG_USERNAME.txt
      - ENVIRONMENT.html


Delete Scratch Org:
  stage: delete-scratch
  only:
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
      - $DEPLOY_SCRATCH_ON_EVERY_COMMIT == 'true'
  except:
    variables:
      - $SCRATCH_DISABLED
  when: manual
  allow_failure: false
  dependencies:
    - Deploy Scratch Org
  script:
    - delete_scratch_org "`cat SCRATCH_ORG_USERNAME.txt`"


# TODO: test this with tags instead of a branch

Deploy to Sandbox:
  stage: deploy-sandbox
  only:
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
  except:
    variables:
      - $SANDBOX_DISABLED
  environment:
    name: sandbox
    #url: https://sandbox.$SFDC_BASE_DOMAIN.salesforce.com
  script:
    - setup_sfdx
    - get_package_name_and_id
    - build_package_version
    - install_package_version HUB_ORG_ALIAS
    - populate_url_artifact HUB_ORG_ALIAS
    - echo "$environment_html" > ENVIRONMENT.html
  artifacts:
    paths:
      - ENVIRONMENT.html


Deploy to Production:
  stage: deploy-production
  only:
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
  except:
    variables:
      - $PRODUCTION_DISABLED
  when: manual
  allow_failure: false
  environment:
    name: production
    #url: https://$SFDC_BASE_DOMAIN.salesforce.com
  script:
    - setup_sfdx
    - get_package_name_and_id
    - build_package_version
    - install_package_version HUB_ORG_ALIAS
    - populate_url_artifact HUB_ORG_ALIAS
    - echo "$environment_html" > ENVIRONMENT.html
  artifacts:
    paths:
      - ENVIRONMENT.html


.sfdx_helpers: &sfdx_helpers |


  # Always call setup_sfdx first

  setup_sfdx () {

    # Decrypt server key
    openssl aes-256-cbc -d -md md5 -in server.key.enc -out server.key -k $SERVER_KEY_PASSWORD

    # Install jq
    apt update && apt -y install jq

    # Setup SFDX environment variables
    export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    export SFDX_AUTOUPDATE_DISABLE=false
    export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    export SFDX_DOMAIN_RETRY=300
    export SFDX_DISABLE_APP_HUB=true
    export SFDX_LOG_LEVEL=DEBUG
    export ROOTDIR=force-app/main/default/
    export TESTLEVEL=RunLocalTests
    export PACKAGEVERSION=""

    # Install Salesforce CLI
    mkdir sfdx
    wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
    "./sfdx/install"
    export PATH=./sfdx/$(pwd):$PATH

    # Output CLI version and plug-in information
    sfdx --version
    sfdx plugins --core

    # Authenticate using JWT
    sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HUB_ORG_ALIAS
  }


  # Function to get package name and ID

  get_package_name_and_id () {
    export package_name=$PACKAGE_NAME
    if [ ! $package_name ]; then
      export package_name=$(cat sfdx-project.json | jq -r '.packageDirectories[] | select(.default==true) | .package')
    fi
    if [ ! $package_name ]; then
      export package_name=$(cat sfdx-project.json | jq -r '.packageDirectories | .[0] | .package')
    fi
    sfdx force:package:list --json
    export package_id=$(sfdx force:package:list --json | jq -r '.result[] | select(.Name==env.package_name) | .Id')
  }


  # Function to check whether there are daily scratch orgs left -- pass targetusername as argument

  check_daily_scratch_orgs () {
    local limits=`sfdx force:limits:api:display -u $1 --json`
    local dso=`jq '.result[] | select(.name == "DailyScratchOrgs")' <<< $limits`
    local dsomax=`jq '.max' <<< $dso`
    local dsorem=`jq '.remaining' <<< $dso`
    if [ $dsorem -le 0 ]; then
      echo "ERROR: Limit of $dsomax Daily Scratch Orgs reached"
    else
      echo "$dsorem of $dsomax Daily Scratch Orgs previously created - OK to proceed"
    fi
    return $(( $dsorem <= 0 ))
  }


  # Function to build a package version

  build_package_version () {
    local output=$(sfdx force:package:version:create --package $package_name --installationkeybypass --wait 10 --json --targetdevhubusername HUB_ORG_ALIAS)
    if [ ! $output ]; then exit 1; fi
    local subscriber_package_version_id=$(jq ".result.SubscriberPackageVersionId" -r <<< $output)
    echo "$subscriber_package_version_id" > SUBSCRIBER_PACKAGE_VERSION_ID.TXT
  }


  # Install a package version -- pass targetusername as argument -- assumes package ID is stored

  install_package_version () {
    sfdx force:package:install --package "`cat SUBSCRIBER_PACKAGE_VERSION_ID.TXT`" --wait 10 --publishwait 10 --targetusername $1 --noprompt
  }


  # Populate the URL artifact with HTML to redirect to an environment
  # TODO: Make this work for scratch orgs too
  # - Pass targetusername as argument

  populate_url_artifact() {
    local url=$(sfdx force:org:display -u $1 --json | jq -r ".result.instanceUrl")
    environment_html='<script>window.onload=function(){window.location.href="$url"}</script>'
  }


  # Create a scratch org
  # - Pass targetusername (HUB_ORG_ALIAS) as argument
  # - Assumes there is a config/project-scratch-def.json file
  # - Sets $scratch_org_username
  # TODO: Remember scratch org username for the branch

  create_scratch_org() {
    local output=$(sfdx force:org:create --targetdevhubusername HUB_ORG_ALIAS --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 1 --json)
    scratch_org_username="$(jq -r '.result.username' <<< $output)"
  }


  # Push to scratch org
  # Assumes username is available in SCRATCH_ORG_USERNAME.txt

  push_to_scratch_org_and_test () {
    if [ ! $scratch_org_username ]; then exit 1; fi
    sfdx force:source:push --targetusername $scratch_org_username
    #sfdx force:user:permset:assign --targetusername `cat SCRATCH_ORG_USERNAME.txt` --permsetname ______
    #sfdx force:data:tree:import --plan data/sample-data-plan.json
    #sfdx force:apex:test:run --targetusername $scratch_org_username --wait 10 --resultformat human --codecoverage --testlevel _________
  }


  # Delete a scratch org
  # Pass in the scratch_org_username

  delete_scratch_org () {
    if [ ! $1 ]; then exit 1; fi
    sfdx force:data:record:delete --sobjecttype ScratchOrgInfo --targetusername HUB_ORG_ALIAS --where "SignupUsername='$1'"
  }


before_script:
  - *sfdx_helpers



# --------------------------- LEGACY STUFF -------------------------------------

#
# Create Scratch Org for code testing -- Stage 1
#
.legacy-code-testing:
  stage: code-testing
  except:
    variables:
      - $SCRATCH_ORG_DISABLED
  script:

    # Authenticate to the Dev Hub using the server key
    - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HUB_ORG_ALIAS

    # Create scratch org
    - sfdx force:org:create --targetdevhubusername HUB_ORG_ALIAS --setdefaultusername --definitionfile config/project-scratch-def.json --setalias $SCRATCH_ORG_ALIAS --wait 10 --durationdays 1
    - sfdx force:org:display --targetusername $SCRATCH_ORG_ALIAS

    # Push source to scratch org (This is with source code, all files, etc)
    - sfdx force:source:push --targetusername $SCRATCH_ORG_ALIAS

    # Assign dreamhouse permission set to scratch org default user
    - sfdx force:user:permset:assign --targetusername $SCRATCH_ORG_ALIAS --permsetname dreamhouse

    # Add sample data into app
    - sfdx force:data:tree:import --plan data/sample-data-plan.json

    # Unit Testing
    - sfdx force:apex:test:run --targetusername $SCRATCH_ORG_ALIAS --wait 10 --resultformat human --codecoverage --testlevel $TESTLEVEL

    # Delete Scratch Org
    - sfdx force:org:delete --targetusername $SCRATCH_ORG_ALIAS --noprompt

#
# Create a Scratch Org, create a package/artifact and push into org for testing
#
.leagcy-integration-testing:
  except:
    variables:
      - $SCRATCH_ORG_DISABLED
  artifacts:
    paths:
      - PACKAGE_VERSION_ID.TXT
      - SCRATCH_ORG_USERNAME.TXT
  stage: integration-testing
  script:

    # Authenticate to the Dev Hub using the server key
    - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HUB_ORG_ALIAS

    ## Create scratch org
    - sfdx force:org:create --targetdevhubusername HUB_ORG_ALIAS --setdefaultusername --definitionfile config/project-scratch-def.json --setalias $SCRATCH_ORG_ALIAS --wait 10 --durationdays 1
    - sfdx force:org:display --targetusername $SCRATCH_ORG_ALIAS
    ## Create packaged version
    - export PACKAGE_VERSION_ID="$(eval sfdx force:package:version:create --package $PACKAGE_NAME --installationkeybypass --wait 10 --json --targetdevhubusername HUB_ORG_ALIAS | jq '.result.SubscriberPackageVersionId' | tr -d '"')"
    ## Save your PACKAGE_VERSION_ID to a file for later use during deploy so we know what version to deploy
    - echo "$PACKAGE_VERSION_ID" > PACKAGE_VERSION_ID.TXT

    ## Install package in DevHub org (this is a compiled library of the app)
    - sfdx force:package:list
    - sfdx force:package:install --package $PACKAGE_VERSION_ID --wait 10 --publishwait 10 --targetusername $SCRATCH_ORG_ALIAS --noprompt

    ## Assign dreamhouse permission set to scratch org default user
    - sfdx force:user:permset:assign --targetusername $SCRATCH_ORG_ALIAS --permsetname dreamhouse

    ## Add sample data into app
    - sfdx force:data:tree:import --plan data/sample-data-plan.json

    ## Run unit tests in scratch org
    - sfdx force:apex:test:run --targetusername $SCRATCH_ORG_ALIAS --wait 10 --resultformat human --codecoverage --testlevel $TESTLEVEL

    ## Get the username for the scratch org
    - export SCRATCH_ORG_USERNAME="$(eval sfdx force:user:display --targetusername $SCRATCH_ORG_ALIAS --json | jq -r '.result.username')"
    - echo "$SCRATCH_ORG_USERNAME" > ./SCRATCH_ORG_USERNAME.TXT

    ## Generate a new password for the scrach org
    - sfdx force:user:password:generate
    - echo -e "\n\n\n\n"

    ## Display username, password, and instance URL for login
    - sfdx force:user:display


# Delete the scratch org to keep everything clean

.leagacy-Delete Scratch Org:
  except:
    variables:
      - $SCRATCH_ORG_DISABLED
  stage: app-deploy
  when: manual
  script:
    - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HUB_ORG_ALIAS
    - sfdx force:data:record:delete --sobjecttype ScratchOrgInfo --targetusername HUB_ORG_ALIAS --where "SignupUsername='`cat ./SCRATCH_ORG_USERNAME.TXT`'"


#
# Promote the package to downstream environment for UAT for example
#
.leagcy-Deploy to Production:
  stage: app-deploy
  when: manual
  only: ['master']
  script:
    - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HUB_ORG_ALIAS
    - sfdx force:package:install --package "`cat PACKAGE_VERSION_ID.TXT`" --wait 10 --publishwait 10 --targetusername HUB_ORG_ALIAS --noprompt
